noun=input("Enter a noun: ")
adjective=input("Enter an adjective: ")
verb=input("Enter a verb: ")
food=input("Enter a food: ")
sport=input("Enter a sport: ")
noun2=input("Enter a noun: ")
verb2=input("Enter a verb: ")
animal=input("Enter an animal: ")
food2=input("Enter a food: ")
print(f"It was a wonderful day, when a {noun} went out for a {adjective} walk outside. After that, he ate {food} and played {sport}. On the {noun}'s way home, he met his friend {noun2} and they decided to {verb2} for a bit before leaving. When the {noun} finally got home, he found his pet {animal} on the couch so he sat right next to his pet. For dinner, they ate {food2} and then fell asleep.")